### ISSUE TITLE
Keep track of tkinter widgets?

### ISSUE THREAD

**Issue by rdbende** [rdbende/flake8-tkinter#10]
Currently `flake8-tkinter` assumes that only tkinter widgets can have methods like `config`, `bind` or `mainloop`.

For things like `w.update` or `w["blah"]` this won't be enough, because we don't want to warn on a dictionary update, or subscript for example.

**Comment by Akuli** [comment]
I would avoid this. A general rule for linters seems to be that if your lint requires you to know the type of something, it should be a type checker plugin and not a linter. Predicting from the user's type annotations isn't great either, because handling things like `list[tkinter.Label]` would be a big part of what type checkers do.

Not knowing whether something is a widget might be fine:
- `widget.update()` and `some_dict.update(other_dict)` are easy to distinguish: one takes arguments, the other does not.
- `widget["blah"]` is somewhat uncommon and mostly hard to mess up.
- `.config()` and `.configure()` might be more likely to collide with other things. But most user-defined functions are typically called with a positional argument like `.configure(some_kind_of_configuration_object)`. Tkinter's `.config()`/`.configure()` only takes keyword arguments. (It actually takes a positional argument too, but nobody ever uses it that way.)
- `.bind()` is tricky. It could conflict with e.g. `socket.bind()` if you do network programming. Checking for `.bind("<...` and `.bind(f"<...` is not always enough, Porcupine has this:
  ```python3
  widget.bind(shift_tab, functools.partial(callback, True), **bind_kwargs)  # noqa: TK231
  ```
- Consider a `mainloop()` or `foobar.mainloop()` in a tkinter program that isn't tkinter's event loop. It will very likely have several properties that make it oddly specific, unlikely to occur in practice:
    - Written by someone who uses old-fashioned naming style (most Python programmers now would name it `main_loop()`)
    - Calls lots of other methods (otherwise there would be no need to call it the "main" thing)
    - Long-running (otherwise it wouldn't be any kind of main thing)
    - Takes no arguments
    - Runs in a thread or subprocess (otherwise it would freeze the GUI)
    - Called directly from another method (not with `threading.Thread(target=mainloop)`, as the flake8-tkinter plugin would ignore that)
    - Terminates with some kind of exit flag (if it didn't, your tkinter program would be impossible to exit)

**Comment by Akuli** [comment]
For `.bind()`, flake8-tkinter somehow manages to not error for the unrelated socket bind.
```
(env) akuli@akuli-desktop:~/porcu$ grep bind tests/test_pastebin_plugin.py
        termbin.bind(("localhost", 0))

(env) akuli@akuli-desktop:~/porcu$ python3 -m flake8 --select=TK tests/

(env) akuli@akuli-desktop:~/porcu$ 
```

**Comment by rdbende** [comment]
> For .bind(), flake8-tkinter somehow manages to not error for the unrelated socket bind.

Probably it's because of the 1-arg checking thingy

**Comment by rdbende** [comment]
Thanks @Akuli for your comments!
This gives me a bit of hope, that the plugin won't be complete garbage :)
